### ISSUE TITLE
Cant be instaled

### ISSUE THREAD

**Issue by fajarwahyu99** [danielsdeboer/Helpdesk#86]
Why is this cant be installed?

**Comment by danielsdeboer** [comment]
What's the issue you're having during installation?

**Comment by fajarwahyu99** [comment]
because artisan not include in this file

**Comment by danielsdeboer** [comment]
How are you trying to install it? This isn't a stand-alone Laravel install. It's meant to be pulled in via Composer.

**Comment by fajarwahyu99** [comment]
i will try again. How much table database in here?

**Comment by danielsdeboer** [comment]
Look in `resources/migrations` for all the database migrations.
